name: Launch test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    test:
        runs-on: ${{ matrix.os }}
        # Uncomment if you want to see all results for all OSses. Otherwise, the first failed test cancels all others
        # continue-on-error: true
        strategy:
            matrix:
                # We test quite a lot of versions because we do some OS and version specific things unfortunately
                julia-version: ["lts", "1"]
                os: [windows-latest, ubuntu-latest]

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4

            # Makes thes `julia` command available
            - uses: julia-actions/setup-julia@v2
              with:
                  version: ${{ matrix.julia-version }}

            # ðŸš—
            - name: Test launch Pluto
              run: |
                  echo "hello world"
                  julia ${{ github.workspace }}/test/run_notebook.jl ${{ github.workspace }}
