name: Windows launch test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        paths-ignore:
            - "frontend/**"
            - "**.md"
    pull_request:
        paths-ignore:
            - "frontend/**"
            - "**.md"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    test:
        runs-on: ${{ matrix.os }}
        # Uncomment if you want to see all results for all OSses. Otherwise, the first failed test cancels all others
        # continue-on-error: true
        strategy:
            matrix:
                # We test quite a lot of versions because we do some OS and version specific things unfortunately
                julia-version: ["1.5"]
                os: [windows-latest]

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            # - uses: actions/checkout@v2

            # Makes thes `julia` command available
            - uses: julia-actions/setup-julia@v1
              with:
                  version: ${{ matrix.julia-version }}

            # ðŸš—
            - name: Test launch Pluto
              run: |
                  echo "hello world"
                  julia $GITHUB_WORKSPACE/test/run_notebook.jl $GITHUB_WORKSPACE
